---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-family.yml"
  when: ansible_os_family == 'Debian'

- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_os_family == 'RedHat'
