---

- name: Install prerequisites with apt
  apt:
    name: "{{ tvheadend_prerequisites }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install prerequisites with yum
  yum:
    name: "{{ tvheadend_prerequisites }}"
    state: present
    update_cache: true
  when: ansible_distribution == "CentOS"

- name: Install prerequisites with dnf
  dnf:
    name: "{{ tvheadend_prerequisites }}"
    state: present
  when: ansible_distribution == "Fedora"
