---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: tvheadend-CentOS7
    image: lansible/centos:7

  - name: tvheadend-Debian9
    image: lansible/debian:9

  - name: tvheadend-Debian8
    image: lansible/debian:8

#  - name: tvheadend-Fedora27
#    image: lansible/fedora:27
#
#  - name: tvheadend-Fedora26
#    image: lansible/fedora:26
#
#  - name: tvheadend-Fedora25
#    image: lansible/fedora:26

  - name: tvheadend-Ubuntu1604
    image: lansible/ubuntu:16.04

provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

scenario:
  name: default
